version: "3.9"
services:
  postgres:
    image: postgres:16-alpine
    container_name: lineage-postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: lineage_api
    ports:
      - "5432:5432"
    volumes:
      - lineage_pgdata:/var/lib/postgresql/data

  lineage-api:
    build: ./services/lineage-api
    container_name: lineage-api
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/lineage_api?schema=public
      PORT: 3001
    ports:
      - "3001:3001"

volumes:
  lineage_pgdata:
